var exc = [
	{id:"llnaliffojpdabmolloonfkjimkjflcg",title:"Mashable News Notifier",link:"http://bit.ly/bqktu1"},
	{id:"mdonfjaemnemdnnpebbcelibeocdmkai",title:"The Independent News Notifier",link:"http://bit.ly/azgknT"},
	{id:"bpnefknkmjpofoapejabiadcgjaafgjd",title:"ReadWriteWeb News Notifier",link:"http://bit.ly/dBkZMn"},
	{id:"cegndnhglpfbacbbjcmeejdoinjgiaae",title:"Huffington Post News Notifier",link:"http://bit.ly/d3a2wH"},
	{id:"kmchifknbnnofpklgjohpiacgbghdjge",title:"Techcrunch News Notifier",link:"http://bit.ly/9SMWzl"},
	{id:"ghlkcbmoicfncbihdpfaikgaonekelde",title:"E!Online News Notifier",link:"http://bit.ly/c8mVch"},
	{id:"gfjagdckhokfnbikcdadlfcebeclecpj",title:"Ars Technica News Notifier",link:"http://bit.ly/bYzQHj"},
	{id:"agbghcdpcpiiijcipfpgfdkfpohddceo",title:"Newsweek News Notifier",link:"http://bit.ly/dxFDBH"},
	{id:"ciajakjjdopefddbfcjpiabklfjjdmjn",title:"Wired News Notifier",link:"http://bit.ly/aqRO9R"},
	{id:"imgfngnbphmpaojdogojahnaoackiogm",title:"AOL News Notifier",link:"http://bit.ly/a533mg"},
	{id:"nkoglaghclgcpmanabneijhllcfckpap",title:"Times Online News Notifier",link:"http://bit.ly/aOE6Tn"},	
	{id:"gegbfkbjdbjmbjggbneiopjmhjjmffdp",title:"Telegraph News Notifier",link:"http://bit.ly/9lOdiR"},	
	{id:"amckaikgfcndaokapfcedicfmagoghlg",title:"Guardian News Notifier",link:"http://bit.ly/9ACLDD"},	
	{id:"ocjdpemfbnpogoejbbenkooiimnehdlb",title:"CNET News Notifier",link:"http://bit.ly/c4opxq"},	
	{id:"piaagpfopkmnmddehfppblapllldicbl",title:"CNN News Notifier",link:"http://bit.ly/9SMWzl"},	
	{id:"mcjhojbgbffgpdmpcpjppaholnkhdpeh",title:"Daily Mail News Notifier",link:"http://bit.ly/bKSaFk"},	
	{id:"fampnmnfdebhlnecpiojjbejnnnjifch",title:"GamesRadar News Notifier",link:"http://bit.ly/axbucj"},	
	{id:"hpclkokgpalhbdiggebndpicfpmdbmfo",title:"Idiomag News Notifier",link:"http://bit.ly/9CS59J"},	
	{id:"haahfmbidghnpkjkedgpolpjghedfcna",title:"IGN News Notifier",link:"http://bit.ly/8Z2tZ4"},	
	{id:"cocifcalgchodoikaadjoakoikponcle",title:"LA Times News Notifier",link:"http://bit.ly/bkHp7X"},	
	{id:"klgeknoggomnggledomclkmajdbagmlf",title:"New York Times News Notifier",link:"http://bit.ly/a5OrlF"},	
	{id:"ionjjdkjodnppkndmldgnbombgeginho",title:"San Francisco Chronicle News Notifier",link:"http://bit.ly/b8Ldh0"},	
	{id:"lffbbkfcdoccioifngmngnbbiefiffba",title:"The Onion News Notifier",link:"http://bit.ly/bLX5KD"},	
	{id:"pllnidelbohpehdbpjgoiiafcjbceepf",title:"USA Today News Notifier",link:"http://bit.ly/dh5NND"},	
	{id:"ipomgempnkndmcgaagoldkbpdpmedbkh",title:"Washington Post News Notifier",link:"http://bit.ly/avntpQ"},	
	{id:"fcmchhlcpjohfcphghmfgfboifdkklhm",title:"WSJ News Notifier",link:"http://bit.ly/9xpsMN"},	
	{id:"nbkjgckanjpbdmffcenbbikhngpnadep",title:"ChromePlay",link:"http://bit.ly/9DM75D"},
	{id:"nfddebdieimglcclnchkjmfeekkeppja",title:"Yolink",link:"http://bit.ly/dsqkPk"}
];